# This is YAML config.yaml file is used to generate the JSON config.json file.
# Make any changes to this file, not the JSON one.
# Run `make update` to regenerate the JSON file.

language: YAMLScript
slug: yamlscript
active: false

status:
  concept_exercises: false
  test_runner: false
  representer: false
  analyzer: false

blurb:
  YAMLScript is a dynamic, general purpose programming language.
  It has a clean YAML syntax and embeds nicely into existing YAML files, making
  the desired parts of them dynamic.
  When a YAMLScript program is run, the source code transpiles to Clojure code,
  and is evaluted by a native binary runtime interpreter called `ys` (not by
  the JVM).
  YAMLScript is also available as a dynamic YAML loader library

version: 3

online_editor:
  indent_style: space
  indent_size: 2

files:
  solution: []
  test: []
  example: []
  exemplar: []

exercises:
  concept: []
  practice:
  - slug: hello-world
    name: Hello World
    uuid: 5279db5b-86f3-4074-9513-36a88c5ef9fc
    practices: []
    prerequisites: []
    difficulty: 1
    topics: [strings]

concepts: []

key_features: []
tags:
- execution_mode/compiled
- execution_mode/interpreted
- paradigm/declarative
- paradigm/functional
- paradigm/imperative
- platform/linux
- platform/mac
# - platform/windows  # soon
# - runtime/jvm  # soon
- runtime/standalone_executable
- typing/dynamic
- used_for/backends
- used_for/cross_platform_development
- used_for/games
- used_for/scientific_calculations
- used_for/scripts

