name: Configlet

on:
  push:
    # branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  configlet:
    uses: exercism/github-actions/.github/workflows/configlet.yml@main
