name: Exercism YAMLScript Track / Test

on:
  push:
    # branches: [main]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-repository:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - run: pwd
      - run: whoami
      - run: sudo apt-get update
      - run: sudo apt-get install -y apt-utils
      - run: |
          sudo apt-get install -y \
            curl \
            jq \
            make \
            perl \
            wget \
            xz-utils

      - name: Install dependencies
        run: make deps

      - name: Run checks and tests
        env:
          EXERCISM_YAMLSCRIPT_GHA: 1
        run: make check
